RaceTrackAssessment/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RaceTrackAssessment.Models
{
    public class Car
    {
       
        [Key]
        public int CarId { get; set; }

        public string CarName { get; set; }

        public string Model { get; set; }

        public bool TowStrap { get; set; }

        public double GroundHeight { get; set; }

        public int TireWear { get; set; }
        public OnTrackCar OnTrackCar { get; set; }

      

    }


}

RaceTrackAssessment/Models/OnTrackCar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RaceTrackAssessment.Models
{
    public class OnTrackCar
    {
        [Key]
        public int TrackID { get; set; }
        public string TrackName { get; set; }
        public List<Car> Cars { get; set; }
       
    }
}

RaceTrackAssessment/Models/ResponceData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RaceTrackAssessment.Models
{
    /// <summary>
    ///  this class will be use to send resonce back to front-end
    /// </summary>
    public class ResponceData
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
    }
}

RaceTrackAssessment/ViewModels/RaceTrackCarViewModel.cs
using RaceTrackDAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RaceTrackAssessment.ViewModels
{
    public class RaceTrackCarViewModel
    {
   
        public int CarId { get; set; }
        public string CarName { get; set; }
        public string Model { get; set; }
        public bool TowStrap { get; set; }
        public double GroundHeight { get; set; }
        public int TireWear { get; set; }

        public RaceTrackCarViewModel(int carId, string carName, string model, bool towStrap, double groundHeight, int tireWear)
        {
            CarId = carId;
            CarName = carName;
            Model = model;
            TowStrap = towStrap;
            GroundHeight = groundHeight;
            TireWear = tireWear;
        }
    }
}

RaceTrackAssessment/Controllers/RaceTrackController.cs
using RaceTrackAssessment.ViewModels;
using RaceTrackDAL.Models;
using RaceTrackService.Service;
using System.Collections.Generic;
using System.Web.Mvc;

namespace RaceTrackAssessment.Controllers
{
    public class RaceTrackController : Controller
    {
        private readonly ICar _ICar;
        private readonly IOnTrackCar _ITrack;

        public RaceTrackController(ICar CarRepo,IOnTrackCar OnTrack) 
        { 
            _ICar = CarRepo; 
            _ITrack = OnTrack; 
        }

        // GET: RaceTrack
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult LoadTracks()
        {
            List<Car> TrackCar = _ITrack.GetOnTrackCars();
            List<RaceTrackCarViewModel> TrackView = new List<RaceTrackCarViewModel>();

            foreach (Car c in TrackCar) 
            {
                TrackView.Add(new RaceTrackCarViewModel(c.CarId,c.CarName,c.Model,c.TowStrap,c.GroundHeight,c.TireWear));
            }

           return Json(TrackView, JsonRequestBehavior.AllowGet);
        }
        //// GET: RaceTrack/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: RaceTrack/Create
        [HttpPost]
        public ActionResult Create(RaceTrackCarViewModel car)
        {
           return Json(_ITrack.AddCarOnTrack(new Car(car.CarName, car.Model, car.TowStrap, car.GroundHeight, car.TireWear)));
        }
    }
}

RaceTrackAssessment/Views/RaceTrack/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/AjaxScript/Car.js"></script>

    <title>Index</title>
</head>
<body>
 
    <div class="container">
        <h2>On Track Cars</h2>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" onclick="clearTextBox();">Add Car on Track</button><br /><br />
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        Car ID
                    </th>
                    <th>
                        Car Name
                    </th>
                    <th>
                        Car Model
                    </th>
                    <th>
                        Tow Strap
                    </th>
                    <th>
                        Groun Height
                    </th>
                    <th>
                       Tire Wear
                    </th>
                </tr>
            </thead>
            <tbody class="tbody">
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title" id="myModalLabel">Add Car</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="CarId">ID</label>
                            <input type="text" class="form-control" id="CarId" placeholder="Car Id" disabled="disabled" />
                        </div>
                        <div class="form-group">
                            <label for="CarName">Car Name</label>
                            <input type="text" class="form-control" id="CarName" placeholder="Car Name" />
                        </div>
                        <div class="form-group">
                            <label for="CarModel">Car Model</label>
                            <input type="text" class="form-control" id="CarModel" placeholder="Car Model" />
                        </div>
                        <div class="form-group">
                            <label for="TowStrap">Tow Strap</label>
                            <input type="text" class="form-control" id="TowStrap" placeholder="On Track" />
                        </div>
                        <div class="form-group">
                            <label for="GHeight">Ground Height</label>
                            <input type="text" class="form-control" id="GHeight" placeholder="On Track" />
                        </div>
                        <div class="form-group">
                            <label for="TireWear">Tire Wear</label>
                            <input type="text" class="form-control" id="TireWear" placeholder="On Track" />
                        </div>
                    
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">Add</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

RaceTrackAssessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Race Track", "Index", "RaceTrack")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>